version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - .env
    networks:
    - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata: