version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: